# Generated by Django 6.0.5 on 2026-05-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='helium_reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=20)),
                ('title', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('seller_creation_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_sales', models.IntegerField(blank=True, null=True)),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image_count', models.IntegerField(blank=True, null=True)),
                ('bsr', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='agents.researchproject')),
            ],
        ),
    ]
